# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='地区')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.AreaModel', verbose_name='所属地区')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'db_table': 't_area',
            },
        ),
        migrations.CreateModel(
            name='ScenicSpotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='景点')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('hot', models.IntegerField(default=0, verbose_name='热度')),
                ('address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('summary', models.TextField(verbose_name='介绍')),
                ('cover', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='封面')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.AreaModel', verbose_name='所属地区')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
                'db_table': 't_scenicspot',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, unique=True, verbose_name='级别')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '标签',
                'ordering': ['-add_time', 'level'],
                'verbose_name_plural': '标签',
                'db_table': 't_tag',
            },
        ),
        migrations.AddField(
            model_name='scenicspotmodel',
            name='tags',
            field=models.ManyToManyField(to='place.TagModel', verbose_name='标签'),
        ),
    ]
